import type { ImageSourcePropType } from "react-native";

export const CARD_BACK_IMAGE: ImageSourcePropType = require("../../assets/cards/back.png");

export const CARD_IMAGES: Record<string, ImageSourcePropType> = {
  "denari-1": require("../../assets/cards/denari-1.png"),
  "denari-2": require("../../assets/cards/denari-2.png"),
  "denari-3": require("../../assets/cards/denari-3.png"),
  "denari-4": require("../../assets/cards/denari-4.png"),
  "denari-5": require("../../assets/cards/denari-5.png"),
  "denari-6": require("../../assets/cards/denari-6.png"),
  "denari-7": require("../../assets/cards/denari-7.png"),
  "denari-8": require("../../assets/cards/denari-8.png"),
  "denari-9": require("../../assets/cards/denari-9.png"),
  "denari-10": require("../../assets/cards/denari-10.png"),
  "coppe-1": require("../../assets/cards/coppe-1.png"),
  "coppe-2": require("../../assets/cards/coppe-2.png"),
  "coppe-3": require("../../assets/cards/coppe-3.png"),
  "coppe-4": require("../../assets/cards/coppe-4.png"),
  "coppe-5": require("../../assets/cards/coppe-5.png"),
  "coppe-6": require("../../assets/cards/coppe-6.png"),
  "coppe-7": require("../../assets/cards/coppe-7.png"),
  "coppe-8": require("../../assets/cards/coppe-8.png"),
  "coppe-9": require("../../assets/cards/coppe-9.png"),
  "coppe-10": require("../../assets/cards/coppe-10.png"),
  "spade-1": require("../../assets/cards/spade-1.png"),
  "spade-2": require("../../assets/cards/spade-2.png"),
  "spade-3": require("../../assets/cards/spade-3.png"),
  "spade-4": require("../../assets/cards/spade-4.png"),
  "spade-5": require("../../assets/cards/spade-5.png"),
  "spade-6": require("../../assets/cards/spade-6.png"),
  "spade-7": require("../../assets/cards/spade-7.png"),
  "spade-8": require("../../assets/cards/spade-8.png"),
  "spade-9": require("../../assets/cards/spade-9.png"),
  "spade-10": require("../../assets/cards/spade-10.png"),
  "bastoni-1": require("../../assets/cards/bastoni-1.png"),
  "bastoni-2": require("../../assets/cards/bastoni-2.png"),
  "bastoni-3": require("../../assets/cards/bastoni-3.png"),
  "bastoni-4": require("../../assets/cards/bastoni-4.png"),
  "bastoni-5": require("../../assets/cards/bastoni-5.png"),
  "bastoni-6": require("../../assets/cards/bastoni-6.png"),
  "bastoni-7": require("../../assets/cards/bastoni-7.png"),
  "bastoni-8": require("../../assets/cards/bastoni-8.png"),
  "bastoni-9": require("../../assets/cards/bastoni-9.png"),
  "bastoni-10": require("../../assets/cards/bastoni-10.png")
};
